spring.application.name=spring-ai
spring.main.banner-mode=off
spring.main.web-application-type=none
spring.jmx.enabled=false

spring.ai.openai.apiKey=${OPENAI_API_KEY}
spring.ai.openai.model=gpt-5.4-mini

logging.level.sun.rmi.transport.tcp=ERROR
